language: node_js
node_js:
  - 8
cache:
  directories:
    - $HOME/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

script: npm run $COMMAND

jobs:
  include:
    - stage: lint
      env: COMMAND=pretest
    - stage: test
      env: COMMAND=test
    - env: COMMAND=test:e2e
    - stage: release
      node_js: lts/*
      env: COMMAND=semantic-release
      deploy:
        script: scripts/deploy.sh
        provider: script
        skip_cleanup: true
  allow_failures:
    - node_js: lts/*
      env: COMMAND=coverage:upload

stages:
  - lint
  - test
  - name: release
    if: branch = master AND type IN (push)
